/*
 * Oracle dump harness for SortSam (SAM I/O, coordinate and queryname orders) conformance in
 * picard-rs.
 *
 * Emits an escaped TSV to stdout: an `input` row (the unsorted SAM), a `coordinate` row and a
 * `queryname` row (the SortSam outputs). The committed corpus is `java ... SortSamDump | gzip > ...`,
 * regenerated and compared in CI. SortSam changes only the header's SO field and adds no @PG and no
 * timestamp, so every SAM is compared raw.
 *
 * The input is generated by htsjdk (so it is already canonical) with reads out of both coordinate
 * and queryname order, across two contigs, including a reverse-strand read at a shared position.
 *
 *   java -cp picard-fat.jar:. SortSamDump
 */
import htsjdk.samtools.*;

import java.io.File;
import java.nio.file.Files;

public class SortSamDump {
    public static void main(final String[] args) throws Exception {
        final SAMRecordSetBuilder builder = new SAMRecordSetBuilder(true, SAMFileHeader.SortOrder.unsorted);
        builder.setRandomSeed(0);
        final int chr1 = builder.getHeader().getSequenceIndex("chr1");
        final int chr2 = builder.getHeader().getSequenceIndex("chr2");
        // Out of order by both name and coordinate; two reads share chr1:100 with opposite strands.
        builder.addFrag("r3", chr1, 500, false);
        builder.addFrag("r1", chr2, 100, false);
        builder.addFrag("r2", chr1, 100, false);
        builder.addFrag("r2b", chr1, 100, true); // reverse strand at the same position as r2

        final File input = File.createTempFile("sortsam-in-", ".sam");
        input.deleteOnExit();
        final SAMFileWriter w = new SAMFileWriterFactory().makeSAMWriter(builder.getHeader(), false, input);
        for (final SAMRecord rec : builder.getRecords()) w.addAlignment(rec);
        w.close();

        emit("input", "case", new String(Files.readAllBytes(input.toPath())));
        emit("coordinate", "case", sorted(input, "coordinate"));
        emit("queryname", "case", sorted(input, "queryname"));
    }

    private static String sorted(final File input, final String order) throws Exception {
        final File out = File.createTempFile("sortsam-" + order + "-", ".sam");
        out.deleteOnExit();
        final int rc = new picard.sam.SortSam().instanceMain(new String[] {
                "INPUT=" + input.getAbsolutePath(),
                "OUTPUT=" + out.getAbsolutePath(),
                "SORT_ORDER=" + order,
        });
        if (rc != 0) {
            System.err.println("SortSam exited " + rc);
            System.exit(rc);
        }
        return new String(Files.readAllBytes(out.toPath()));
    }

    private static void emit(final String kind, final String kase, final String payload) {
        final String esc = payload.replace("\\", "\\\\").replace("\t", "\\t").replace("\n", "\\n");
        System.out.println(kind + "\t" + kase + "\t" + esc);
    }
}
